import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { AiFillLinkedin, AiFillGithub } from 'react-icons/ai';
import { HiOutlineMail } from 'react-icons/hi';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Centered Navbar with icons */}
        <nav className="w-full flex justify-center items-center gap-8 mb-12 mt-4 text-lg font-serif">
          <div className="flex gap-8 items-center">
            <Link href="/" className="hover:text-gray-700 transition">home</Link>
            <Link href="/resume" className="hover:text-gray-700 transition">resume</Link>
            <a href="https://www.linkedin.com/in/pynay/" target="_blank" rel="noopener noreferrer" className="hover:scale-110 transition-transform"><AiFillLinkedin className="text-foreground" size={28} /></a>
            <a href="https://github.com/pynay" target="_blank" rel="noopener noreferrer" className="hover:scale-110 transition-transform"><AiFillGithub className="text-foreground" size={28} /></a>
            <a href="mailto:pyalamanchali@ucsd.edu" className="hover:scale-110 transition-transform"><HiOutlineMail className="text-foreground" size={28} /></a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
